### ISSUE TITLE
Add a way to load collections in another bucket

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-wizard#45]
If I have the following yaml file:

```
chefclub:
    collections:
        categories:
                ...
```

I'd like to be able to use `kinto-wizard` to load this file in `chefclub-preview` rather than `chefclub`

    kinto-wizard load recipes.yaml --bucket "chefclub:chefclub-preview"

or

    kinto-wizard load recipes.yaml --bucket "chefclub" --dest-bucket "chefclub-preview"

What do you think?

Right now I just do:

    sed -i "s/chefclub:/chefclub-preview:/g" recipes.yaml
