### ISSUE TITLE
Check if anchor and references are supported in YAML files

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-wizard#52]
Would be useful for schema definitions etc.

Example taken from stackoverflow:

```yaml
version: '2'
dummy: &deploy_template
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 10
    window: 120s
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    deploy: *deploy_template
    volumes:
      - /srv/redis/data:/data
```

turned to

```yaml
version: '2'
dummy:
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 10
    window: 120s
services:
  redis:
    image: redis
    ports:
    - 6379:6379
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    volumes:
    - /srv/redis/data:/data
```
