### ISSUE TITLE
Permissions replacement is confusing and dangerous

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-wizard#66]
Scenario.

My YAML contains this:

```yml
buckets:
  test:
    permissions:
      collection:create:
      - account:bob
```
I load it `kinto-wizard load /tmp/test.yaml --server http://localhost:8888/v1 --auth user:pass`. A `PUT` is sent.

Then I want to remove the collection create permission and rewrite my YAML as this:

```yml
buckets:
  test:
    permissions:
      write:
      - account:alice
```
And I load it `kinto-wizard load /tmp/test.yaml --server http://localhost:8888/v1 --auth user:pass`. A `PATCH` is sent.

At this point I would expect the permission to create collection was removed... but...

```
$ http :8888/v1/buckets/test -a user:pass
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Cache-Control, Pragma, Expires, Content-Length, Backoff, Retry-After, ETag, Alert, Last-Modified
Cache-Control: no-cache, no-store
Content-Length: 207
Content-Type: application/json
Date: Fri, 07 Dec 2018 22:19:30 GMT
Etag: "1544221156019"
Last-Modified: Fri, 07 Dec 2018 22:19:16 GMT
Server: waitress
X-Content-Type-Options: nosniff

{
    "data": {
        "id": "test",
        "last_modified": 1544221156019
    },
    "permissions": {
        "collection:create": [
            "account:bob"
        ],
        "write": [
            "basicauth:7afa16e9e220bdca1f8fa1839c9cb7dc29cffbd148756908894ed8add8d1ced8",
            "account:alice"
        ]
    }
}
```

It was not removed!

/cc @glasserc
